[package]
name = "devtools-demo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "devtools-demo"
path = "src/main.rs"

[dependencies]
leptos-sync-core = { path = "../../leptos-sync-core" }
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
