[build]
# Enable incremental compilation for faster builds
incremental = true

# Use multiple jobs for compilation
jobs = 4

[target.wasm32-unknown-unknown]
# Optimize WASM output for size and performance
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=--export-table",
    "-C", "link-arg=--import-memory",
]

[profile.release]
# Optimize for size in release builds
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
# Faster compilation in development
opt-level = 0
debug = true
incremental = true

[profile.test]
# Optimize tests for speed
opt-level = 1
debug = true
incremental = true

[alias]
# Useful cargo aliases
test-all = "test --workspace"
check-all = "check --workspace"
build-all = "build --workspace"
clean-all = "clean --workspace"
